### PR TITLE
Update the new star rating and rebalance

### PR DESCRIPTION
**Pull request by wasupandceacar**
I update the new star rating and rebalance refered to oppai. At the same time, I add a method to parse a certain part of the map. (for realtime calculated pp and its almost used in my repo _(:з」∠)_)

### CODE REVIEW

**Comment by flesnuk** [comment]
Reviewing it. I don't have that much time in weekdays, so maybe I will update on next weekend.

**Comment by wasupandceacar** [comment]
Seems that oppai will update to 3.0 soon, so maybe more updates are going to be added. If the new slider calculation is not that complex I will try to rewrite it.

**Comment by wasupandceacar** [comment]
Seems that oppai 3.0 still doesn't add slider calculation, so I decide to update the only commit ahead this pr(see this [https://github.com/Francesco149/koohii/commit/30e0f1a6a711f9a59b32a638d045bf139b0332e0](https://github.com/Francesco149/koohii/commit/30e0f1a6a711f9a59b32a638d045bf139b0332e0)). You can review it in my new pr.

**Comment by wasupandceacar** [comment]
Seems that oppai 3.0 still doesn't add slider calculation, so I decide to update the only commit ahead this pr(see this [https://github.com/Francesco149/koohii/commit/30e0f1a6a711f9a59b32a638d045bf139b0332e0](https://github.com/Francesco149/koohii/commit/30e0f1a6a711f9a59b32a638d045bf139b0332e0)). Now its pp result should be as same as oppai 3.0 I think.

**Comment by flesnuk** [comment]
Yeah, I know, I will merge your PR today. If we need to implement slider calc or improve precision, will do it in another PR.

Thank you for your contribution!

**Pull request merged**
