### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by diamondburned**
Things refactored:
- Parser is rewritten by [tdeo](https://git.sr.ht/~tdeo/pp/tree), ported over by me
- Changed some functions to use traditional Go stdlib ones
- Separated `Vector2` into `package vector`
- Changed to `float64` for better accuracy
- Some more tests were made to compare
- Changed the names of some files to match their contents better
- Utilize `go.mod`
- Changed snake_case names to camelCase 
- Tweaked some variable names
- Made pointer several structs/fields
- Converted some methods into functions
- Removed the redundant `PPv2Parameters` struct
- Added a `Mods` field into `PPv2` for easier access and tests
- Last but not least: replaced all `panic`s with proper errors, I don't want my application to crash because of some idiots

### Warning! This PR will definitely break existing code! Which is why `go.mod` should be here.

Edit: old vs new round functions compared: https://play.golang.org/p/aYu5fXmtIo6

### CODE REVIEW

**Comment by flesnuk** [comment]
Thank you so much for taking time and putting this MR together. 

When I wrote oppai5 and copied the code from the java version, I didn't think much about the API or proper error handling because I wanted done it quick and only for my other repo "biku". 
And since I didn't have much time and stopped playing osu!, I lost motivation to fix it.

I quickly reviewed the changes and it seems good to me. As you saw, there was some ugly code (use of unsafe or for i loops) in there because of performance (see #1) , so I don't know exactly how will differ until I benchmark it. I will remove unsafe code since it wasn't that much faster and it was dumb in using it in the first case

**Comment by diamondburned** [comment]
I've done some benchmarks a while ago here:



Edit1: In some cases, I've seen you using `i` loops and declaring a variable right after, which beats the point. I did, however, made some things a pointer, which should mean that declaring a variable no longer copies the old one.

**Comment by diamondburned** [comment]
20 days later... Will this be merged?

**Comment by flesnuk** [comment]
Sorry, I didn't have time to look into this. Too much IRL stuff to do T_T

**Pull request closed without merging**
